"""empty message

Revision ID: 14a5823f1b76
Revises: fa5135555809
Create Date: 2022-03-01 08:11:06.223970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a5823f1b76'
down_revision = 'fa5135555809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lower_card', sa.Integer(), nullable=True),
    sa.Column('upper_card', sa.Integer(), nullable=True),
    sa.Column('lower_wins', sa.Integer(), nullable=True),
    sa.Column('upper_wins', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lower_card'], ['card.id'], ),
    sa.ForeignKeyConstraint(['upper_card'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pairs')
    # ### end Alembic commands ###
