"""empty message

Revision ID: 9fe72cdb8440
Revises: 14a5823f1b76
Create Date: 2022-03-01 08:13:22.380773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe72cdb8440'
down_revision = '14a5823f1b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pair',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lower_card', sa.Integer(), nullable=True),
    sa.Column('upper_card', sa.Integer(), nullable=True),
    sa.Column('lower_wins', sa.Integer(), nullable=True),
    sa.Column('upper_wins', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lower_card'], ['card.id'], ),
    sa.ForeignKeyConstraint(['upper_card'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pairs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('lower_card', sa.INTEGER(), nullable=True),
    sa.Column('upper_card', sa.INTEGER(), nullable=True),
    sa.Column('lower_wins', sa.INTEGER(), nullable=True),
    sa.Column('upper_wins', sa.INTEGER(), nullable=True),
    sa.Column('ties', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['lower_card'], ['card.id'], ),
    sa.ForeignKeyConstraint(['upper_card'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pair')
    # ### end Alembic commands ###
